/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.supercom.util.auto.label;

/**
 * A trans counter is an object that counts particular features of transitions.
 * For instance, a trans counter can be used to count the number of observations
 * generated by a trajectory.  Each trans label is independent.  
 *
 * @author Alban Grastien
 */
public interface TransCounter<TL> {

    /**
     * Gives a counting number to the specified trans label.
     *
     * @param label the label on which the counting is performed.
     * @return an integer value corresponding to the number of features in the
     * label.
     */
    public int count(TL label);

}
