package diag.reiter2.log;

/**
 * A <code>Logger</code>, i.e., a logger, 
 * is an object that is decides what to do with the logs 
 * generated by the diagnoser.  
 */
public interface Logger {
    
    /**
     * Sends the specified log to this logger.  
     * 
     * @param log the log generated by the diagnoser.  
     */
    public void log(Log log);
    
}
